duckdb/duckdb-postgres

postgres_scanner.cpp, test/postgres_scanner/count_star.test
This query only requires counting rows, so it is optimized into selecting a rowid column from the underlying table. In case of the Postgres table, this gets deparsed into selecting the first column. If it happens to be a text column, we then try to insert it into the rowid output vector which is int, and fail with an assertion because of type mismatch.
Instead of this, deparse this case into SELECT NULL FROM postgres_table. This is enough for counting the rows.
=> Fix SELECT count(*)

postgres_scanner.cpp
Removing these for my eventual PR to DuckDB where I move the JSON LogicalType into the JSON extension.
=> Remove LogicalType::JSON from switch cases

all_pg_types.sql, postgres_scanner.cpp, test/postgres_scanner/types.test
Uses `hugeint_t` data type to represent UUID from postgres.
Adds test cases for "nil uuid", lowercase, uppercase, and `NULL`.
Fixes #25
=> support uuid type

postgres_scanner.cpp, test/all_pg_types.sql
This pull request fixes an issue where enum array columns would fail with because of an empty namespace value:
```
07:23:45     ERROR:  syntax error at or near "."
07:23:45    LINE 1: SELECT unnest(enum_range(NULL::.my_enum_type))
```
For some reason, there is a condition that throws an error if an array value's length doesn't match its `typlen` value. This doesn't make sense since Postgres arrays are variable length. Existing array tests seem to pass without it.
I added some additional unit tests for enum arrays. Github Actions was slow to start so pasting test output from my machine:
```
[100%] Built target postgres_scanner_loadable_extension
./build/release/test/unittest --test-dir . "[postgres_scanner]"
Filters: [postgres_scanner]
[17/17] (100%): test/postgres_scanner/bug76.test …
```
=> Fix enum array support

concurrency_test.cpp, postgres_scanner.cpp
This PR is made in preparation of migrating DuckDB to use it's own `unique_ptr` implementation
Removing the use of `std::make_unique` and changing it to `duckdb::make_uniq`
`make_unique` -> `make_uniq` is done to avoid clashing with the std namespace and having to explicitly qualify every call.
=> Safe unique ptr

src/include/postgres_connection.hpp, src/include/postgres_scanner.hpp, src/include/postgres_utils.hpp, src/include/postgres_version.hpp, src/include/storage/postgres_catalog.hpp, src/postgres_connection.cpp, src/postgres_scanner.cpp, src/postgres_storage.cpp, src/postgres_utils.cpp, src/storage/postgres_catalog.cpp, src/storage/postgres_table_entry.cpp, test/sql/storage/attach_non_existent.test
=> Fix #90 - disable parallel scans for read-only replicas

src/postgres_scanner.cpp
=> Fix #113: Add missing std::move for old GCC

CMakeLists.txt, Makefile
Fixes builds that run through CMake so the Postgres files are correctly fetched
=> Build Fix - run execute_process from within CMake

CMakeLists.txt, src/include/postgres_version.hpp, src/postgres_scanner.cpp, test/sql/storage/attach_insert_from_scan_large.test
Fixes #118
Makes it so that scans are run in parallel when running a `CREATE TABLE` also without setting `preserve_insertion_order`
=> Add support for batch indexes to the Postgres scanner

src/include/postgres_connection.hpp, src/include/postgres_result.hpp, src/include/postgres_scanner.hpp, src/postgres_connection.cpp, src/postgres_query.cpp, src/postgres_scanner.cpp
Fixes #125, #129
These functions are not critical so failing when they are not supported is unnecessary
=> Use TryQuery for getting recovery/snapshot information

src/include/postgres_binary_reader.hpp, test/all_pg_types.sql, test/sql/storage/bug136.test
=> Fix #136 - correctly deal with decimals that have many leading zeros

src/include/postgres_version.hpp, src/postgres_connection.cpp, src/postgres_scanner.cpp
Follow-up fix to #134, should solve more issues around AWS Aurora
=> Detect that we are connected with Aurora, and avoid running snapshot code with Aurora in general

.github/workflows/MainDistributionPipeline.yml, src/include/postgres_connection.hpp, src/include/postgres_scanner.hpp, src/include/storage/postgres_catalog.hpp, src/include/storage/postgres_catalog_set.hpp, src/include/storage/postgres_connection_pool.hpp, src/include/storage/postgres_index_set.hpp, src/include/storage/postgres_schema_entry.hpp, src/include/storage/postgres_schema_set.hpp, src/include/storage/postgres_table_set.hpp, src/include/storage/postgres_transaction.hpp, src/include/storage/postgres_type_set.hpp, src/postgres_connection.cpp, src/postgres_query.cpp, src/postgres_scanner.cpp, src/postgres_storage.cpp, src/storage/postgres_catalog.cpp, src/storage/postgres_connection_pool.cpp, src/storage/postgres_index_set.cpp, src/storage/postgres_schema_entry.cpp, src/storage/postgres_schema_set.cpp, src/storage/postgres_table_entry.cpp, src/storage/postgres_table_set.cpp, src/storage/postgres_transaction.cpp, src/storage/postgres_type_set.cpp, vcpkg.json
This PR reduces the number of round-trips and reconnects that happen in the Postgres attach and subsequent queries through the following mechanisms:
* Turn the connection pool into an actual connection pool that caches Postgres connections, avoiding the need to reconnect for every transaction
* Avoids running BEGIN TRANSACTION/COMMIT as separate statements unnecessarily when reading small tables
* Fetch the schema/tables/types/indexes in one single set of queries send through `PQsendQuery` instead of running multiple separate queries that incur a round-trip every time
* Fetch enums/composite types and their info in a single query instead of fetching them in two batches (previously we had two queries: (1) figured out which enums existed, (2) figured out the enum values).
Using the [RNA …
=> Keep connections cached, and reduce round-trips

src/include/postgres_connection.hpp, src/postgres_connection.cpp, src/postgres_scanner.cpp
=> Fix #154: keep transaction open for legacy postgres_scan function

src/include/storage/postgres_catalog_set.hpp, src/include/storage/postgres_table_set.hpp, src/include/storage/postgres_type_set.hpp, src/storage/postgres_catalog_set.cpp, src/storage/postgres_schema_entry.cpp, src/storage/postgres_table_set.cpp, test/sql/storage/attach_concurrent_queries.test
If a new table is created from within Postgres, the table should now be immediately visible in DuckDB without having to run `CALL pg_clear_cache()`.
=> Try to reload a table/view definition from Postgres if a table/view is not found

src/include/storage/postgres_connection_pool.hpp, src/postgres_extension.cpp, src/storage/postgres_connection_pool.cpp, test/sql/storage/attach_connection_pool.test
#142 introduced a connection cache - however, keeping connections cached is not super trivial because there is state associated with an open connection. I suspect that this might be causing some issues, so this marks the connection cache as experimental. It can be enabled with a setting (`SET pg_experimental_connection_cache=true`) and is disabled by default for now.
=> Add setting pg_experimental_connection_cache that is disabled by default

.github/workflows/MainDistributionPipeline.yml, test/sql/storage/attach_types.test
Fixes https://github.com/duckdb/postgres_scanner/pull/191.
I have removed all newly added types to test_all_types, but this might not be strictly needed since some of them might be supported. To be reviewed whether some can be added back.
=> Bump DuckDB to v0.10.1

src/CMakeLists.txt, src/include/postgres_scanner.hpp, src/postgres_execute.cpp, src/postgres_extension.cpp, test/sql/storage/attach_postgres_execute.test, test/sql/storage/attach_read_only.test
Usage:
```sql
ATTACH 'dbname=postgresscanner' AS s (TYPE POSTGRES);
CALL postgres_execute('s', 'CREATE TABLE my_table(i INTEGER)');
```
=> Add support for a new postgres_execute function that can be used to execute arbitrary queries within Postgres

src/include/postgres_version.hpp, src/postgres_connection.cpp, src/postgres_utils.cpp
=> Fix #181 - use version() instead, and if version query fails default to unknown version

src/include/postgres_binary_reader.hpp, src/include/storage/postgres_schema_entry.hpp, src/include/storage/postgres_table_set.hpp, src/postgres_extension.cpp, src/postgres_scanner.cpp, src/storage/postgres_catalog_set.cpp, src/storage/postgres_index.cpp, src/storage/postgres_optimizer.cpp, src/storage/postgres_schema_entry.cpp, src/storage/postgres_schema_set.cpp, src/storage/postgres_table_set.cpp, test/other.sql, test/sql/storage/attach_existing_constraints.test
Fix #190 
When querying table information from postgres, also query the `pg_constraint` table to find unique/primary key constraints.
=> Fix #190 - Query constraints from Postgres metadata

src/CMakeLists.txt, src/include/postgres_binary_copy.hpp, src/include/postgres_binary_writer.hpp, src/postgres_binary_copy.cpp, src/postgres_extension.cpp, test/sql/misc/postgres_binary.test
Implements #204
This PR adds support for the `POSTGRES_BINARY` copy format, that allows you to write files in the [Postgres binary format](https://www.postgresql.org/docs/current/sql-copy.html). The files can be subsequently copied into Postgres using their `FORMAT binary` copy method.  Example use case:
```sql
D create table integers(i int);
D insert into integers from range(100);
D copy integers to 'pg_binary.bin' (format postgres_binary);
```
```sql
postgres=# create table integers(i int);
postgres=# copy integers from '/{working_directory}/pg_binary.bin' (format binary);
postgres=# SELECT COUNT(*), MIN(i), MAX(i), SUM(i) FROM integers;
count | min | max | sum  
-------+-----+-----+------
100 |   0 |  99 | 4950
(1 row)
```
This uses the `PostgresBinaryWriter` that we have developed. …
=> Implement #204 - Add support for POSTGRES_BINARY copy method

src/include/postgres_text_writer.hpp, src/postgres_copy_to.cpp, test/sql/storage/attach_backslash.test
=> Fix #202 - correctly escape backslashes in Postgres text copy

src/storage/postgres_table_entry.cpp, test/sql/storage/attach_text_array.test
=> Fix #206 - use text copy when the oid we generate does not match the internal oid for the type

src/postgres_extension.cpp, src/postgres_storage.cpp, test/sql/storage/attach_secret.test
Implements #213
This allows credentials to be managed using secrets. The secret to be used can be selected with the `SECRET` setting that is passed into `ATTACH`. There is also a default secret - this is the secret that is created without specifying a name. When no secret is provided to `ATTACH`, and such a secret is present, this secret is used.
Secrets can provide the following set of options.
|    Name    |             Description              |
|------------|--------------------------------------|
| `dbname`   | Database name                        |
| `database` | Alias for dbname                     |
| `user`     | Postgres user name                   |
| `password` | Postgres password                    |
| `host`     | Name of host to connect to           |
| `port`     | Port …
=> Allow Postgres credentials to be managed using the SecretManager

src/postgres_copy_to.cpp, test/sql/storage/attach_types_lists.test, test/sql/storage/attach_types_struct.test
Sorry for the uncalled for PR, but I had a patch we were using, so I figured I could offer it. Bare in mind that I'm not a C++ person, so it might be completely misguided :D.
This PR changes the way how lists and structs are copied to postgres when the text mode is active. Previously, no escaping was performed on the members of lists and structs. This meant that whenever we were trying to copy a value which contained a character used to encode either structs or lists, we'd end up with invalid literals. This made it impossible to copy:
1. Lists containing the empty string
2. Lists containing whitespace-only string
3. Lists containing strings containing curly braces, commas or quotes
4. Structs containing strings containing braces, commas or quotes
5. Combinations of all of the above …
=> Fix copy to postgres for lists and structs in text mode.

src/include/storage/postgres_transaction.hpp, src/storage/postgres_catalog.cpp, src/storage/postgres_table_entry.cpp, src/storage/postgres_transaction.cpp, test/sql/storage/attach_temporary_table.test
Fixes #225 
Add support for the `pg_temp` schema by replacing `pg_temp` with the actual `pg_temp_XX` schema - found through the query:
```sql
SELECT nspname FROM pg_namespace WHERE oid = pg_my_temp_schema();
````
If `pg_temp` is used before it is instantiated, we force instantiation in Postgres by creating a temporary table using the query:
```sql
CREATE TEMPORARY TABLE __internal_temporary_table(i INTEGER)
```
=> Fix #225 - add support for pg_temp

.github/workflows/MainDistributionPipeline.yml, src/include/storage/postgres_delete.hpp, src/include/storage/postgres_insert.hpp, src/include/storage/postgres_update.hpp, src/postgres_extension.cpp, src/storage/postgres_delete.cpp, src/storage/postgres_insert.cpp, src/storage/postgres_update.cpp
There are some issues with the tests performed by Linux.yml, that needs to be looked at.
Note that some might be already there since the move to duckdb v1.0.0.
Given these are preexisting, and bumping version do not preclude compilation / problem is minor, I think this can go in independently.
=> Bump to latest duckdb, absorb patches

src/postgres_query.cpp, src/postgres_scanner.cpp, test/sql/scanner/aws-rds.test, test/sql/storage/attach_temporary_table.test, test/sql/storage/attach_types.test
* Set table functions to `TableFunctionInitialization::INITIALIZE_ON_SCHEDULE` - the materialization logic in the global source state requires us to do this *before* execution
* Skip varint in `test_all_types`
* Skip a few tests for now
=> Fixes for new DuckDB version

src/storage/postgres_table_set.cpp, test/sql/storage/attach_create_uppercase_names.test
=> Fix #250 - always quote column names in CREATE TABLE to avoid Postgres' lowercasing them

src/postgres_copy_to.cpp, test/sql/storage/attach_varchar_list_nulls.test
=> Fix #242: correctly reset varchar chunk when casting data in CopyChunk

src/postgres_execute.cpp, test/sql/storage/postgres_execute_transaction.test
Fixes #222 
This is a strange behavior in `libpq` - when executing a `COPY`, the connection enters a copy mode, and there seems to be no way of exiting this. `PQsendQuery` fails with the `another command is already in progress` error if the connection is in `COPY` mode, but somehow `PQexec` has no problem running queries. Since we don't care about the result set when using `postgres_execute` we can just call `PQexec` instead.
=> Fix #222: use PQexec instead of PQsendQuery for postgres_execute

src/include/storage/postgres_catalog.hpp, src/include/storage/postgres_index_set.hpp, src/include/storage/postgres_schema_set.hpp, src/include/storage/postgres_type_set.hpp, src/postgres_storage.cpp, src/storage/postgres_catalog.cpp, src/storage/postgres_index_set.cpp, src/storage/postgres_schema_set.cpp, src/storage/postgres_type_set.cpp, test/other.sql, test/sql/storage/attach_schema_param.test
Fixes #221 
This adds the `SCHEMA` parameter to `ATTACH`, which (1) limits the catalog entries that are loaded to only those in that schema, and (2) sets that schema as the default schema (instead of `public`). For example:
```sql
ATTACH 'dbname=postgresscanner' AS s (TYPE POSTGRES, SCHEMA 'some_schema');
SELECT * FROM s.some_table; -- reads from s.some_schema.some_table;
```
When there are many schemas in a database, this can speed up the attach as only a single schema's catalog entries are fetched.
=> Fix #221: add the SCHEMA parameter to ATTACH that allows you to specify which schema to load

src/postgres_utils.cpp, test/sql/storage/attach_ubigint.test
=> Fix  #246 - convert ubigint to `decimal(20,0)` instead of to double to avoid loss of precision

src/include/postgres_binary_reader.hpp, src/postgres_copy_from.cpp, test/sql/storage/attach_timeout_error.test
Fixes #270
The issue is that Postgres can return `-1` from `PQgetCopyData` (indicating the COPY is finished). This is almost always due to an error. We would previously throw a non-descriptive error here - we now fetch the actual error using `PQgetResult`.
For example:
```sql
ATTACH 'dbname=postgresscanner options=''-c statement_timeout=10000''' AS s (TYPE POSTGRES, READ_ONLY);
SELECT * FROM postgres_query(s, 'select count(*) from tbl, tbl t2');
```
This now throws the following error:
```
IO Error: Failed to fetch header for COPY: ERROR:  canceling statement due to statement timeout
```
=> Fix #270: print a more descriptive error message when PQgetCopyData returns -1 (no error and no header/data)

src/include/postgres_utils.hpp, src/postgres_utils.cpp, src/storage/postgres_delete.cpp, src/storage/postgres_index_set.cpp, src/storage/postgres_schema_entry.cpp, src/storage/postgres_update.cpp, test/sql/storage/attach_upper_case.test
=> Fix #284: quote uppercase identifiers when shipping queries to Postgres

src/postgres_scanner.cpp
This clutters the debug logs with unnecessary whitespace otherwise
=> Remove indentations in COPY queries

.github/workflows/MainDistributionPipeline.yml, CMakeLists.txt
This should be mostly a nop, but allow postgres_scanner to be explicitly compatible with newer cmake versions.
=> Widen range of cmake_minimum_required

src/storage/postgres_optimizer.cpp, test/sql/storage/limit.test
https://github.com/duckdb/duckdb-postgres/issues/328
LIMIT pushdown was added to this extension. https://github.com/duckdb/duckdb-postgres/pull/313  
It pushes LIMIT down to Postgres and removes it from the DuckDB query plan.
Problem is that parallelism can occur in the extension, and one Query gets turned into n postgres queries. Pushing LIMIT down then falsifies the result.
A test is added, using `set pg_pages_per_task=1`, that reproduces this by forcing parallelism.  
I added a check on `max_threads`, which makes it so that LIMIT is NOT pushed down, if it is anything other than `1`. 
This should prevent LIMIT from being pushed down in any case where we would have parallel queries from the best of my knowledge. **(There could be a better way to check for parallelism that I am not aware …
=> Fix #328 - Dont do limit pushdown during parallel execution

src/postgres_binary_reader.cpp, src/postgres_connection.cpp, src/postgres_copy_from.cpp, src/postgres_copy_to.cpp
In a bunch of cases PQclear was not being called on a (possibly)
initialized `PGresult *`. This fixes those cases. These are all fairly
small memory leaks, but they could add up over time if multiple queries
to Postgres are being done.
=> Fix various memory leaks

src/include/postgres_binary_reader.hpp, src/include/postgres_scanner.hpp, src/postgres_binary_reader.cpp, src/postgres_connection.cpp, src/postgres_copy_from.cpp, src/postgres_copy_to.cpp, src/postgres_query.cpp, src/postgres_scanner.cpp, src/storage/postgres_table_entry.cpp, test/sql/scanner/postgres_query_error.test
Fixes #344 
After running a binary copy we need to run `PQgetResult` until we no longer get back a result (not just once as is indicated in the docs). If we do not do this - the connection remains in a busy state and unable to process further queries. This does not matter in most cases because we open a new connection per transaction anyway - but when explicitly opening a transaction we re-use the same connection. 
In addition, this PR also fixes an issue where `pg_use_text_protocol` was not respected for `postgres_query` and `postgres_scan`.
=> Fix #344: correctly finish binary copy in Postgres result reading to reset the connection back to idle

src/include/postgres_connection.hpp, src/postgres_connection.cpp, test/sql/storage/attach_show_all_tables.test
Fixes #341 
The Postgres connection object is not thread-safe, we need to add an explicit mutex to the connection.
=> Fix #341: add mutex to querying using Postgres connection
